(ns marketplace-aggregator.craigslist
  (:require [clojure.string :as string]
            [clj-http.client :as http]
            [marketplace-aggregator.models :as models]
            [net.cgrand.enlive-html :as html])
  (:import [java.net URLEncoder]))

(def sites-map {"clovis / portales" "https://clovis.craigslist.org/"
                "rhode island" "https://providence.craigslist.org/"
                "asheville" "https://asheville.craigslist.org/"
                "bowling green" "https://bgky.craigslist.org/"
                "recife" "https://recife.craigslist.org/"
                "wausau" "https://wausau.craigslist.org/"
                "greenville / upstate" "https://greenville.craigslist.org/"
                "virgin islands" "https://virgin.craigslist.org/"
                "outer banks" "https://outerbanks.craigslist.org/"
                "chicago" "https://chicago.craigslist.org/"
                "fortaleza" "https://fortaleza.craigslist.org/"
                "st petersburg" "https://stpetersburg.craigslist.org/"
                "goa" "https://goa.craigslist.co.in/"
                "belgium" "https://brussels.craigslist.org/"
                "delaware" "https://delaware.craigslist.org/"
                "guangzhou" "https://guangzhou.craigslist.com.cn/"
                "malaysia" "https://malaysia.craigslist.org/"
                "bologna" "https://bologna.craigslist.it/"
                "topeka" "https://topeka.craigslist.org/"
                "visalia-tulare" "https://visalia.craigslist.org/"
                "venezuela" "https://caracas.craigslist.org/"
                "dresden" "https://dresden.craigslist.de/"
                "lake charles" "https://lakecharles.craigslist.org/"
                "guanajuato" "https://guanajuato.craigslist.com.mx/"
                "kent" "https://kent.craigslist.co.uk/"
                "normandy" "https://rouen.craigslist.org/"
                "baltimore" "https://baltimore.craigslist.org/"
                "western maryland" "https://westmd.craigslist.org/"
                "southwest TX" "https://bigbend.craigslist.org/"
                "munich" "https://munich.craigslist.de/"
                "bangalore" "https://bangalore.craigslist.co.in/"
                "panama city" "https://panamacity.craigslist.org/"
                "edinburgh" "https://edinburgh.craigslist.co.uk/"
                "billings" "https://billings.craigslist.org/"
                "marseille" "https://marseilles.craigslist.org/"
                "oregon coast" "https://oregoncoast.craigslist.org/"
                "st augustine" "https://staugustine.craigslist.org/"
                "northeast SD" "https://nesd.craigslist.org/"
                "newcastle / NE england" "https://newcastle.craigslist.co.uk/"
                "gainesville" "https://gainesville.craigslist.org/"
                "west virginia (old)" "https://wv.craigslist.org/"
                "twin falls" "https://twinfalls.craigslist.org/"
                "hamilton-burlington" "https://hamilton.craigslist.ca/"
                "des moines" "https://desmoines.craigslist.org/"
                "southwest KS" "https://swks.craigslist.org/"
                "fayetteville" "https://fayetteville.craigslist.org/"
                "gulfport / biloxi" "https://gulfport.craigslist.org/"
                "fort wayne" "https://fortwayne.craigslist.org/"
                "yuba-sutter" "https://yubasutter.craigslist.org/"
                "dubuque" "https://dubuque.craigslist.org/"
                "san diego" "https://sandiego.craigslist.org/"
                "ames" "https://ames.craigslist.org/"
                "western IL" "https://quincy.craigslist.org/"
                "bilbao" "https://bilbao.craigslist.es/"
                "farmington" "https://farmington.craigslist.org/"
                "guelph" "https://guelph.craigslist.ca/"
                "cardiff / wales" "https://cardiff.craigslist.co.uk/"
                "baton rouge" "https://batonrouge.craigslist.org/"
                "sioux city" "https://siouxcity.craigslist.org/"
                "south florida" "https://miami.craigslist.org/"
                "gadsden-anniston" "https://gadsden.craigslist.org/"
                "green bay" "https://greenbay.craigslist.org/"
                "milan" "https://milan.craigslist.it/"
                "kamloops" "https://kamloops.craigslist.ca/"
                "dayton / springfield" "https://dayton.craigslist.org/"
                "kokomo" "https://kokomo.craigslist.org/"
                "north mississippi" "https://northmiss.craigslist.org/"
                "southern illinois" "https://carbondale.craigslist.org/"
                "dothan" "https://dothan.craigslist.org/"
                "corpus christi" "https://corpuschristi.craigslist.org/"
                "bacolod" "https://bacolod.craigslist.com.ph/"
                "whistler" "https://whistler.craigslist.ca/"
                "ciudad juarez" "https://juarez.craigslist.com.mx/"
                "kalamazoo" "https://kalamazoo.craigslist.org/"
                "birmingham / west mids" "https://birmingham.craigslist.co.uk/"
                "eastern CT" "https://newlondon.craigslist.org/"
                "liverpool" "https://liverpool.craigslist.co.uk/"
                "ahmedabad" "https://ahmedabad.craigslist.co.in/"
                "halifax" "https://halifax.craigslist.ca/"
                "cagayan de oro" "https://cdo.craigslist.com.ph/"
                "wichita falls" "https://wichitafalls.craigslist.org/"
                "devon & cornwall" "https://devon.craigslist.co.uk/"
                "new river valley" "https://blacksburg.craigslist.org/"
                "ethiopia" "https://addisababa.craigslist.org/"
                "texarkana" "https://texarkana.craigslist.org/"
                "lancaster" "https://lancaster.craigslist.org/"
                "nicaragua" "https://managua.craigslist.org/"
                "reading" "https://reading.craigslist.org/"
                "wuhan" "https://wuhan.craigslist.com.cn/"
                "cape cod / islands" "https://capecod.craigslist.org/"
                "glasgow" "https://glasgow.craigslist.co.uk/"
                "raleigh / durham / CH" "https://raleigh.craigslist.org/"
                "boise" "https://boise.craigslist.org/"
                "eastern panhandle" "https://martinsburg.craigslist.org/"
                "santa barbara" "https://santabarbara.craigslist.org/"
                "greece" "https://athens.craigslist.gr/"
                "tucson" "https://tucson.craigslist.org/"
                "harrisburg" "https://harrisburg.craigslist.org/"
                "huntington-ashland" "https://huntington.craigslist.org/"
                "stockton" "https://stockton.craigslist.org/"
                "roanoke" "https://roanoke.craigslist.org/"
                "scranton / wilkes-barre" "https://scranton.craigslist.org/"
                "charlotte" "https://charlotte.craigslist.org/"
                "brainerd" "https://brainerd.craigslist.org/"
                "comox valley" "https://comoxvalley.craigslist.ca/"
                "christchurch" "https://christchurch.craigslist.org/"
                "clarksville" "https://clarksville.craigslist.org/"
                "caribbean islands" "https://caribbean.craigslist.org/"
                "shreveport" "https://shreveport.craigslist.org/"
                "red deer" "https://reddeer.craigslist.ca/"
                "dalian" "https://dalian.craigslist.com.cn/"
                "eau claire" "https://eauclaire.craigslist.org/"
                "xi'an" "https://xian.craigslist.com.cn/"
                "fort collins / north CO" "https://fortcollins.craigslist.org/"
                "chillicothe" "https://chillicothe.craigslist.org/"
                "copenhagen" "https://copenhagen.craigslist.org/"
                "san marcos" "https://sanmarcos.craigslist.org/"
                "canarias" "https://canarias.craigslist.es/"
                "iowa city" "https://iowacity.craigslist.org/"
                "sioux falls / SE SD" "https://siouxfalls.craigslist.org/"
                "grand rapids" "https://grandrapids.craigslist.org/"
                "st john's" "https://newfoundland.craigslist.ca/"
                "vienna" "https://vienna.craigslist.at/"
                "missoula" "https://missoula.craigslist.org/"
                "mendocino county" "https://mendocino.craigslist.org/"
                "janesville" "https://janesville.craigslist.org/"
                "gold coast" "https://goldcoast.craigslist.com.au/"
                "hudson valley" "https://hudsonvalley.craigslist.org/"
                "greensboro" "https://greensboro.craigslist.org/"
                "jacksonville" "https://jacksonville.craigslist.org/"
                "skeena-bulkley" "https://skeena.craigslist.ca/"
                "palm beach county" "http://miami.craigslist.org/pbc/"
                "ann arbor" "https://annarbor.craigslist.org/"
                "jackson  " "https://jacksontn.craigslist.org/"
                "sweden" "https://stockholm.craigslist.se/"
                "dublin" "https://dublin.craigslist.org/"
                "okaloosa / walton" "https://okaloosa.craigslist.org/"
                "merced" "https://merced.craigslist.org/"
                "moses lake" "https://moseslake.craigslist.org/"
                "fraser valley" "https://abbotsford.craigslist.ca/"
                "santa fe / taos" "https://santafe.craigslist.org/"
                "nuremberg" "https://nuremberg.craigslist.de/"
                "the thumb" "https://thumb.craigslist.org/"
                "la crosse" "https://lacrosse.craigslist.org/"
                "monterrey" "https://monterrey.craigslist.com.mx/"
                "orange county" "https://orangecounty.craigslist.org/"
                "lincoln" "https://lincoln.craigslist.org/"
                "mohave county" "https://mohave.craigslist.org/"
                "salina" "https://salina.craigslist.org/"
                "western slope" "https://westslope.craigslist.org/"
                "ft mcmurray" "https://ftmcmurray.craigslist.ca/"
                "strasbourg" "https://strasbourg.craigslist.org/"
                "ghana" "https://accra.craigslist.org/"
                "prince edward island" "https://pei.craigslist.ca/"
                "ashtabula" "https://ashtabula.craigslist.org/"
                "stuttgart" "https://stuttgart.craigslist.de/"
                "coventry" "https://coventry.craigslist.co.uk/"
                "beijing" "https://beijing.craigslist.com.cn/"
                "utica-rome-oneida" "https://utica.craigslist.org/"
                "imperial county" "https://imperial.craigslist.org/"
                "prince george" "https://princegeorge.craigslist.ca/"
                "charlottesville" "https://charlottesville.craigslist.org/"
                "tuscaloosa" "https://tuscaloosa.craigslist.org/"
                "northern WI" "https://northernwi.craigslist.org/"
                "kennewick-pasco-richland" "https://kpr.craigslist.org/"
                "binghamton" "https://binghamton.craigslist.org/"
                "montreal" "https://montreal.craigslist.ca/"
                "cairns" "https://cairns.craigslist.com.au/"
                "toulouse" "https://toulouse.craigslist.org/"
                "rio de janeiro" "https://rio.craigslist.org/"
                "north central FL" "https://lakecity.craigslist.org/"
                "altoona-johnstown" "https://altoona.craigslist.org/"
                "monterey bay" "https://monterey.craigslist.org/"
                "nice / cote d'azur" "https://cotedazur.craigslist.org/"
                "myrtle beach" "https://myrtlebeach.craigslist.org/"
                "rochester " "https://rmn.craigslist.org/"
                "lubbock" "https://lubbock.craigslist.org/"
                "twin tiers NY/PA" "https://twintiers.craigslist.org/"
                "southwest michigan" "https://swmi.craigslist.org/"
                "tyler / east TX" "https://easttexas.craigslist.org/"
                "montevideo" "https://montevideo.craigslist.org/"
                "galveston" "https://galveston.craigslist.org/"
                "vancouver" "https://vancouver.craigslist.ca/"
                "worcester / central MA" "https://worcester.craigslist.org/"
                "pakistan" "https://pakistan.craigslist.org/"
                "amarillo" "https://amarillo.craigslist.org/"
                "sheffield" "https://sheffield.craigslist.co.uk/"
                "cologne" "https://cologne.craigslist.de/"
                "provo / orem" "https://provo.craigslist.org/"
                "thailand" "https://bangkok.craigslist.co.th/"
                "las cruces" "https://lascruces.craigslist.org/"
                "cincinnati" "https://cincinnati.craigslist.org/"
                "brownsville" "https://brownsville.craigslist.org/"
                "jacksonville " "https://onslow.craigslist.org/"
                "show low" "https://showlow.craigslist.org/"
                "lucknow" "https://lucknow.craigslist.co.in/"
                "veracruz" "https://veracruz.craigslist.com.mx/"
                "mansfield" "https://mansfield.craigslist.org/"
                "monroe" "https://monroe.craigslist.org/"
                "las vegas" "https://lasvegas.craigslist.org/"
                "macon / warner robins" "https://macon.craigslist.org/"
                "san angelo" "https://sanangelo.craigslist.org/"
                "london" "https://london.craigslist.co.uk/"
                "southwest VA" "https://swva.craigslist.org/"
                "curitiba" "https://curitiba.craigslist.org/"
                "muncie / anderson" "https://muncie.craigslist.org/"
                "south jersey" "https://southjersey.craigslist.org/"
                "nagoya" "https://nagoya.craigslist.jp/"
                "inland empire" "https://inlandempire.craigslist.org/"
                "aberdeen" "https://aberdeen.craigslist.co.uk/"
                "chennai (madras)" "https://chennai.craigslist.co.in/"
                "northwest CT" "https://nwct.craigslist.org/"
                "east midlands" "https://eastmids.craigslist.co.uk/"
                "plattsburgh-adirondacks" "https://plattsburgh.craigslist.org/"
                "morgantown" "https://morgantown.craigslist.org/"
                "pueblo" "https://pueblo.craigslist.org/"
                "yucatan" "https://yucatan.craigslist.com.mx/"
                "faro / algarve" "https://faro.craigslist.pt/"
                "humboldt county" "https://humboldt.craigslist.org/"
                "winnipeg" "https://winnipeg.craigslist.ca/"
                "torino" "https://torino.craigslist.it/"
                "little rock" "https://littlerock.craigslist.org/"
                "pampanga" "https://pampanga.craigslist.com.ph/"
                "huntsville / decatur" "https://huntsville.craigslist.org/"
                "odessa / midland" "https://odessa.craigslist.org/"
                "windsor" "https://windsor.craigslist.ca/"
                "sunshine coast" "https://sunshine.craigslist.ca/"
                "reykjavik" "https://reykjavik.craigslist.org/"
                "zamboanga" "https://zamboanga.craigslist.com.ph/"
                "del rio / eagle pass" "https://delrio.craigslist.org/"
                "port huron" "https://porthuron.craigslist.org/"
                "monroe " "https://monroemi.craigslist.org/"
                "hong kong" "https://hongkong.craigslist.hk/"
                "north platte" "https://northplatte.craigslist.org/"
                "maine" "https://maine.craigslist.org/"
                "high rockies" "https://rockies.craigslist.org/"
                "cedar rapids" "https://cedarrapids.craigslist.org/"
                "bhubaneswar" "https://bhubaneswar.craigslist.co.in/"
                "sicilia" "https://sicily.craigslist.it/"
                "bismarck" "https://bismarck.craigslist.org/"
                "madrid" "https://madrid.craigslist.es/"
                "grand forks" "https://grandforks.craigslist.org/"
                "eastern NC" "https://eastnc.craigslist.org/"
                "san antonio" "https://sanantonio.craigslist.org/"
                "champaign urbana" "https://chambana.craigslist.org/"
                "tunisia" "https://tunis.craigslist.org/"
                "sapporo" "https://sapporo.craigslist.jp/"
                "canberra" "https://canberra.craigslist.com.au/"
                "manchester" "https://manchester.craigslist.co.uk/"
                "oaxaca" "https://oaxaca.craigslist.com.mx/"
                "trois-rivieres" "https://troisrivieres.craigslist.ca/"
                "eugene" "https://eugene.craigslist.org/"
                "parkersburg-marietta" "https://parkersburg.craigslist.org/"
                "panama" "https://panama.craigslist.org/"
                "east oregon" "https://eastoregon.craigslist.org/"
                "osaka-kobe-kyoto" "https://osaka.craigslist.jp/"
                "cookeville" "https://cookeville.craigslist.org/"
                "ocala" "https://ocala.craigslist.org/"
                "eastern montana" "https://montana.craigslist.org/"
                "dunedin" "https://dunedin.craigslist.co.nz/"
                "davao city" "https://davaocity.craigslist.com.ph/"
                "nanaimo" "https://nanaimo.craigslist.ca/"
                "florida keys" "https://keys.craigslist.org/"
                "hampton roads" "https://norfolk.craigslist.org/"
                "denver" "https://denver.craigslist.org/"
                "fort dodge" "https://fortdodge.craigslist.org/"
                "siskiyou county" "https://siskiyou.craigslist.org/"
                "vietnam" "https://vietnam.craigslist.org/"
                "tuscarawas co" "https://tuscarawas.craigslist.org/"
                "treasure coast" "https://treasure.craigslist.org/"
                "quebec city" "https://quebec.craigslist.ca/"
                "salem" "https://salem.craigslist.org/"
                "roseburg" "https://roseburg.craigslist.org/"
                "guam-micronesia" "https://micronesia.craigslist.org/"
                "vermont" "https://vermont.craigslist.org/"
                "southwest MS" "https://natchez.craigslist.org/"
                "decatur" "https://decatur.craigslist.org/"
                "london " "https://londonon.craigslist.ca/"
                "boone" "https://boone.craigslist.org/"
                "frankfurt" "https://frankfurt.craigslist.de/"
                "manila" "https://manila.craigslist.com.ph/"
                "leipzig" "https://leipzig.craigslist.de/"
                "fargo / moorhead" "https://fargo.craigslist.org/"
                "northern panhandle" "https://wheeling.craigslist.org/"
                "south coast" "https://southcoast.craigslist.org/"
                "broward county" "http://miami.craigslist.org/brw/"
                "northwest GA" "https://nwga.craigslist.org/"
                "kerala" "https://kerala.craigslist.co.in/"
                "richmond" "https://richmond.craigslist.org/"
                "ft myers / SW florida" "https://fortmyers.craigslist.org/"
                "space coast" "https://spacecoast.craigslist.org/"
                "beaumont / port arthur" "https://beaumont.craigslist.org/"
                "houston" "https://houston.craigslist.org/"
                "elko" "https://elko.craigslist.org/"
                "knoxville" "https://knoxville.craigslist.org/"
                "melbourne" "https://melbourne.craigslist.com.au/"
                "redding" "https://redding.craigslist.org/"
                "kootenays" "https://kootenays.craigslist.ca/"
                "indore" "https://indore.craigslist.co.in/"
                "montpellier" "https://montpellier.craigslist.org/"
                "owen sound" "https://owensound.craigslist.ca/"
                "memphis" "https://memphis.craigslist.org/"
                "grenoble" "https://grenoble.craigslist.org/"
                "chihuahua" "https://chihuahua.craigslist.com.mx/"
                "phoenix" "https://phoenix.craigslist.org/"
                "lawton" "https://lawton.craigslist.org/"
                "lyon" "https://lyon.craigslist.org/"
                "madison" "https://madison.craigslist.org/"
                "statesboro" "https://statesboro.craigslist.org/"
                "richmond " "https://richmondin.craigslist.org/"
                "oxford" "https://oxford.craigslist.co.uk/"
                "peoria" "https://peoria.craigslist.org/"
                "skagit / island / SJI" "https://skagit.craigslist.org/"
                "state college" "https://pennstate.craigslist.org/"
                "southwest MN" "https://marshall.craigslist.org/"
                "lynchburg" "https://lynchburg.craigslist.org/"
                "lisbon" "https://lisbon.craigslist.pt/"
                "detroit metro" "https://detroit.craigslist.org/"
                "york" "https://york.craigslist.org/"
                "evansville" "https://evansville.craigslist.org/"
                "southern maryland" "https://smd.craigslist.org/"
                "tijuana" "https://tijuana.craigslist.com.mx/"
                "porto" "https://porto.craigslist.pt/"
                "athens" "https://athensga.craigslist.org/"
                "killeen / temple / ft hood" "https://killeen.craigslist.org/"
                "sevilla" "https://sevilla.craigslist.es/"
                "cleveland" "https://cleveland.craigslist.org/"
                "bloomington-normal" "https://bn.craigslist.org/"
                "florence / tuscany" "https://florence.craigslist.it/"
                "essex" "https://essex.craigslist.co.uk/"
                "perth" "https://perth.craigslist.com.au/"
                "hanford-corcoran" "https://hanford.craigslist.org/"
                "finland" "https://helsinki.craigslist.fi/"
                "klamath falls" "https://klamath.craigslist.org/"
                "long island" "https://longisland.craigslist.org/"
                "eastern shore" "https://easternshore.craigslist.org/"
                "lewiston / clarkston" "https://lewiston.craigslist.org/"
                "thunder bay" "https://thunderbay.craigslist.ca/"
                "st george" "https://stgeorge.craigslist.org/"
                "valdosta" "https://valdosta.craigslist.org/"
                "costa rica" "https://costarica.craigslist.org/"
                "southeast IA" "https://ottumwa.craigslist.org/"
                "genoa" "https://genoa.craigslist.it/"
                "toronto" "https://toronto.craigslist.ca/"
                "puebla" "https://puebla.craigslist.com.mx/"
                "delhi" "https://delhi.craigslist.co.in/"
                "essen / ruhr" "https://essen.craigslist.de/"
                "los angeles" "https://losangeles.craigslist.org/"
                "porto alegre" "https://portoalegre.craigslist.org/"
                "kelowna / okanagan" "https://kelowna.craigslist.ca/"
                "prescott" "https://prescott.craigslist.org/"
                "leeds" "https://leeds.craigslist.co.uk/"
                "texoma" "https://texoma.craigslist.org/"
                "montgomery" "https://montgomery.craigslist.org/"
                "palm springs" "https://palmsprings.craigslist.org/"
                "hannover" "https://hannover.craigslist.de/"
                "mattoon-charleston" "https://mattoon.craigslist.org/"
                "jerusalem" "https://jerusalem.craigslist.org/"
                "chongqing" "https://chongqing.craigslist.com.cn/"
                "milwaukee" "https://milwaukee.craigslist.org/"
                "ecuador" "https://quito.craigslist.org/"
                "south dakota" "https://sd.craigslist.org/"
                "finger lakes" "https://fingerlakes.craigslist.org/"
                "haifa" "https://haifa.craigslist.org/"
                "shenyang" "https://shenyang.craigslist.com.cn/"
                "norway" "https://oslo.craigslist.org/"
                "kolkata (calcutta)" "https://kolkata.craigslist.co.in/"
                "budapest" "https://budapest.craigslist.org/"
                "auckland" "https://auckland.craigslist.org/"
                "bloomington" "https://bloomington.craigslist.org/"
                "susanville" "https://susanville.craigslist.org/"
                "new brunswick" "https://newbrunswick.craigslist.ca/"
                "quad cities" "https://quadcities.craigslist.org/"
                "manhattan" "https://ksu.craigslist.org/"
                "southeast missouri" "https://semo.craigslist.org/"
                "erie" "https://erie.craigslist.org/"
                "columbia / jeff city" "https://columbiamo.craigslist.org/"
                "harrisonburg" "https://harrisonburg.craigslist.org/"
                "sault ste marie" "https://soo.craigslist.ca/"
                "sao paulo" "https://saopaulo.craigslist.org/"
                "napoli / campania" "https://naples.craigslist.it/"
                "granada" "https://granada.craigslist.es/"
                "shenzhen" "https://shenzhen.craigslist.com.cn/"
                "malaga" "https://malaga.craigslist.es/"
                "mazatlan" "https://mazatlan.craigslist.com.mx/"
                "wichita" "https://wichita.craigslist.org/"
                "columbia" "https://columbia.craigslist.org/"
                "sendai" "https://sendai.craigslist.jp/"
                "reno / tahoe" "https://reno.craigslist.org/"
                "ogden-clearfield" "https://ogden.craigslist.org/"
                "darwin" "https://darwin.craigslist.com.au/"
                "hermosillo" "https://hermosillo.craigslist.com.mx/"
                "sardinia" "https://sardinia.craigslist.it/"
                "chengdu" "https://chengdu.craigslist.com.cn/"
                "grand island" "https://grandisland.craigslist.org/"
                "battle creek" "https://battlecreek.craigslist.org/"
                "stillwater" "https://stillwater.craigslist.org/"
                "savannah / hinesville" "https://savannah.craigslist.org/"
                "seattle-tacoma" "https://seattle.craigslist.org/"
                "charleston " "https://charlestonwv.craigslist.org/"
                "kuwait" "https://kuwait.craigslist.org/"
                "bern" "https://bern.craigslist.ch/"
                "ottawa-hull-gatineau" "https://ottawa.craigslist.ca/"
                "turkey" "https://istanbul.craigslist.com.tr/"
                "ithaca" "https://ithaca.craigslist.org/"
                "waco" "https://waco.craigslist.org/"
                "jersey shore" "https://jerseyshore.craigslist.org/"
                "saskatoon" "https://saskatoon.craigslist.ca/"
                "pittsburgh" "https://pittsburgh.craigslist.org/"
                "calgary" "https://calgary.craigslist.ca/"
                "surat surat" "https://surat.craigslist.co.in/"
                "bend" "https://bend.craigslist.org/"
                "florence" "https://florencesc.craigslist.org/"
                "indianapolis" "https://indianapolis.craigslist.org/"
                "edmonton" "https://edmonton.craigslist.ca/"
                "lawrence" "https://lawrence.craigslist.org/"
                "yellowknife" "https://yellowknife.craigslist.ca/"
                "baja california sur" "https://bajasur.craigslist.com.mx/"
                "youngstown" "https://youngstown.craigslist.org/"
                "albuquerque" "https://albuquerque.craigslist.org/"
                "east idaho" "https://eastidaho.craigslist.org/"
                "shanghai" "https://shanghai.craigslist.com.cn/"
                "east anglia" "https://norwich.craigslist.co.uk/"
                "lakeland" "https://lakeland.craigslist.org/"
                "colorado springs" "https://cosprings.craigslist.org/"
                "southeast alaska" "https://juneau.craigslist.org/"
                "heartland florida" "https://cfl.craigslist.org/"
                "lafayette / west lafayette" "https://tippecanoe.craigslist.org/"
                "st louis" "https://stlouis.craigslist.org/"
                "holland" "https://holland.craigslist.org/"
                "butte" "https://butte.craigslist.org/"
                "poland" "https://warsaw.craigslist.pl/"
                "chautauqua" "https://chautauqua.craigslist.org/"
                "danville" "https://danville.craigslist.org/"
                "medicine hat" "https://hat.craigslist.ca/"
                "dundee" "https://dundee.craigslist.co.uk/"
                "saguenay" "https://saguenay.craigslist.ca/"
                "united arab emirates" "https://dubai.craigslist.org/"
                "boston" "https://boston.craigslist.org/"
                "pune" "https://pune.craigslist.co.in/"
                "athens " "https://athensohio.craigslist.org/"
                "new haven" "https://newhaven.craigslist.org/"
                "charleston" "https://charleston.craigslist.org/"
                "belo horizonte" "https://belohorizonte.craigslist.org/"
                "yuma" "https://yuma.craigslist.org/"
                "U.S. virgin islands" "https://virgin.craigslist.org/"
                "iraq" "https://baghdad.craigslist.org/"
                "winston-salem" "https://winstonsalem.craigslist.org/"
                "miami / dade" "http://miami.craigslist.org/mdc/"
                "hawaii" "https://honolulu.craigslist.org/"
                "toledo" "https://toledo.craigslist.org/"
                "iran" "https://tehran.craigslist.org/"
                "sacramento" "https://sacramento.craigslist.org/"
                "boulder" "https://boulder.craigslist.org/"
                "kaiserslautern" "https://kaiserslautern.craigslist.de/"
                "west bank" "https://ramallah.craigslist.org/"
                "chandigarh" "https://chandigarh.craigslist.co.in/"
                "tulsa" "https://tulsa.craigslist.org/"
                "lansing" "https://lansing.craigslist.org/"
                "puerto rico" "https://puertorico.craigslist.org/"
                "mcallen / edinburg" "https://mcallen.craigslist.org/"
                "oklahoma city" "https://oklahomacity.craigslist.org/"
                "eastern CO" "https://eastco.craigslist.org/"
                "loire valley" "https://loire.craigslist.org/"
                "fresno / madera" "https://fresno.craigslist.org/"
                "wyoming" "https://wyoming.craigslist.org/"
                "deep east texas" "https://nacogdoches.craigslist.org/"
                "alicante" "https://alicante.craigslist.es/"
                "indonesia" "https://jakarta.craigslist.org/"
                "central NJ" "https://cnj.craigslist.org/"
                "johannesburg" "https://johannesburg.craigslist.co.za/"
                "adelaide" "https://adelaide.craigslist.com.au/"
                "kalispell" "https://kalispell.craigslist.org/"
                "pierre / central SD" "https://csd.craigslist.org/"
                "cumberland valley" "https://chambersburg.craigslist.org/"
                "tampa bay area" "https://tampa.craigslist.org/"
                "lausanne" "https://lausanne.craigslist.ch/"
                "san francisco bay area" "https://sfbay.craigslist.org/"
                "ventura county" "https://ventura.craigslist.org/"
                "cariboo" "https://cariboo.craigslist.ca/"
                "dominican republic" "https://santodomingo.craigslist.org/"
                "logan" "https://logan.craigslist.org/"
                "bath" "https://bath.craigslist.co.uk/"
                "kenosha-racine" "https://racine.craigslist.org/"
                "guatemala" "https://guatemala.craigslist.org/"
                "southern WV" "https://swv.craigslist.org/"
                "geneva" "https://geneva.craigslist.ch/"
                "fayetteville " "https://fayar.craigslist.org/"
                "northwest KS" "https://nwks.craigslist.org/"
                "ukraine" "https://ukraine.craigslist.org/"
                "corvallis/albany" "https://corvallis.craigslist.org/"
                "flint" "https://flint.craigslist.org/"
                "nanjing" "https://nanjing.craigslist.com.cn/"
                "orlando" "https://orlando.craigslist.org/"
                "acapulco" "https://acapulco.craigslist.com.mx/"
                "wenatchee" "https://wenatchee.craigslist.org/"
                "el salvador" "https://elsalvador.craigslist.org/"
                "pretoria" "https://pretoria.craigslist.co.za/"
                "baleares" "https://baleares.craigslist.es/"
                "jaipur" "https://jaipur.craigslist.co.in/"
                "fort smith" "https://fortsmith.craigslist.org/"
                "victoria" "https://victoria.craigslist.ca/"
                "hattiesburg" "https://hattiesburg.craigslist.org/"
                "hampshire" "https://hampshire.craigslist.co.uk/"
                "akron / canton" "https://akroncanton.craigslist.org/"
                "rome" "https://rome.craigslist.it/"
                "wollongong" "https://wollongong.craigslist.com.au/"
                "college station" "https://collegestation.craigslist.org/"
                "joplin" "https://joplin.craigslist.org/"
                "kitchener-waterloo-cambridge" "https://kitchener.craigslist.ca/"
                "el paso" "https://elpaso.craigslist.org/"
                "poconos" "https://poconos.craigslist.org/"
                "chatham-kent" "https://chatham.craigslist.ca/"
                "prague" "https://prague.craigslist.cz/"
                "yakima" "https://yakima.craigslist.org/"
                "morocco" "https://casablanca.craigslist.org/"
                "hiroshima" "https://hiroshima.craigslist.jp/"
                "iloilo" "https://iloilo.craigslist.com.ph/"
                "puerto vallarta" "https://pv.craigslist.com.mx/"
                "lima / findlay" "https://limaohio.craigslist.org/"
                "eastern kentucky" "https://eastky.craigslist.org/"
                "chattanooga" "https://chattanooga.craigslist.org/"
                "zurich" "https://zurich.craigslist.ch/"
                "helena" "https://helena.craigslist.org/"
                "muskegon" "https://muskegon.craigslist.org/"
                "omaha / council bluffs" "https://omaha.craigslist.org/"
                "north dakota" "https://nd.craigslist.org/"
                "lafayette" "https://lafayette.craigslist.org/"
                "romania" "https://bucharest.craigslist.org/"
                "buffalo" "https://buffalo.craigslist.org/"
                "hartford" "https://hartford.craigslist.org/"
                "brunswick" "https://brunswick.craigslist.org/"
                "guadalajara" "https://guadalajara.craigslist.com.mx/"
                "mason city" "https://masoncity.craigslist.org/"
                "kenya" "https://kenya.craigslist.org/"
                "sarasota-bradenton" "https://sarasota.craigslist.org/"
                "kenai peninsula" "https://kenai.craigslist.org/"
                "sherbrooke" "https://sherbrooke.craigslist.ca/"
                "lethbridge" "https://lethbridge.craigslist.ca/"
                "new orleans" "https://neworleans.craigslist.org/"
                "albany " "https://albanyga.craigslist.org/"
                "la salle co" "https://lasalle.craigslist.org/"
                "zanesville / cambridge" "https://zanesville.craigslist.org/"
                "great falls" "https://greatfalls.craigslist.org/"
                "st cloud" "https://stcloud.craigslist.org/"
                "colombia" "https://colombia.craigslist.org/"
                "fort lauderdale" "https://fortlauderdale.craigslist.org/"
                "mobile" "https://mobile.craigslist.org/"
                "croatia" "https://zagreb.craigslist.org/"
                "fairbanks" "https://fairbanks.craigslist.org/"
                "columbus " "https://columbusga.craigslist.org/"
                "heidelberg" "https://heidelberg.craigslist.de/"
                "hangzhou" "https://hangzhou.craigslist.com.cn/"
                "tasmania" "https://hobart.craigslist.com.au/"
                "florence / muscle shoals" "https://shoals.craigslist.org/"
                "peace river country" "https://peace.craigslist.ca/"
                "wilmington" "https://wilmington.craigslist.org/"
                "tokyo" "https://tokyo.craigslist.jp/"
                "upper peninsula" "https://up.craigslist.org/"
                "daytona beach" "https://daytona.craigslist.org/"
                "syracuse" "https://syracuse.craigslist.org/"
                "mumbai" "https://mumbai.craigslist.co.in/"
                "nottingham" "https://nottingham.craigslist.co.uk/"
                "san luis obispo" "https://slo.craigslist.org/"
                "salt lake city" "https://saltlakecity.craigslist.org/"
                "pullman / moscow" "https://pullman.craigslist.org/"
                "north jersey" "https://newjersey.craigslist.org/"
                "columbus" "https://columbus.craigslist.org/"
                "cape town" "https://capetown.craigslist.co.za/"
                "abilene" "https://abilene.craigslist.org/"
                "belleville" "https://belleville.craigslist.ca/"
                "annapolis" "https://annapolis.craigslist.org/"
                "albany" "https://albany.craigslist.org/"
                "basel" "https://basel.craigslist.ch/"
                "mankato" "https://mankato.craigslist.org/"
                "valencia" "https://valencia.craigslist.es/"
                "rochester" "https://rochester.craigslist.org/"
                "catskills" "https://catskills.craigslist.org/"
                "saginaw-midland-baycity" "https://saginaw.craigslist.org/"
                "lexington" "https://lexington.craigslist.org/"
                "brasilia" "https://brasilia.craigslist.org/"
                "augusta" "https://augusta.craigslist.org/"
                "brighton" "https://brighton.craigslist.co.uk/"
                "flagstaff / sedona" "https://flagstaff.craigslist.org/"
                "glens falls" "https://glensfalls.craigslist.org/"
                "watertown" "https://watertown.craigslist.org/"
                "sydney" "https://sydney.craigslist.com.au/"
                "kingston" "https://kingston.craigslist.ca/"
                "hyderabad" "https://hyderabad.craigslist.co.in/"
                "northwest OK" "https://enid.craigslist.org/"
                "louisville" "https://louisville.craigslist.org/"
                "dusseldorf" "https://dusseldorf.craigslist.de/"
                "elmira-corning" "https://elmira.craigslist.org/"
                "cebu" "https://cebu.craigslist.com.ph/"
                "philadelphia" "https://philadelphia.craigslist.org/"
                "kansas city" "https://kansascity.craigslist.org/"
                "barcelona" "https://barcelona.craigslist.es/"
                "singapore" "https://singapore.craigslist.com.sg/"
                "derby" "https://derby.craigslist.co.uk/"
                "olympic peninsula" "https://olympic.craigslist.org/"
                "durban" "https://durban.craigslist.co.za/"
                "mexico city" "https://mexicocity.craigslist.com.mx/"
                "roswell / carlsbad" "https://roswell.craigslist.org/"
                "brisbane" "https://brisbane.craigslist.com.au/"
                "kirksville" "https://kirksville.craigslist.org/"
                "cadiz" "https://cadiz.craigslist.es/"
                "bristol" "https://bristol.craigslist.co.uk/"
                "egypt" "https://cairo.craigslist.org/"
                "oneonta" "https://oneonta.craigslist.org/"
                "hamburg" "https://hamburg.craigslist.de/"
                "laredo" "https://laredo.craigslist.org/"
                "taiwan" "https://taipei.craigslist.com.tw/"
                "paris" "https://paris.craigslist.org/"
                "sudbury" "https://sudbury.craigslist.ca/"
                "bordeaux" "https://bordeaux.craigslist.org/"
                "rapid city / west SD" "https://rapidcity.craigslist.org/"
                "bangladesh" "https://bangladesh.craigslist.org/"
                "fredericksburg" "https://fredericksburg.craigslist.org/"
                "bicol region" "https://naga.craigslist.com.ph/"
                "bozeman" "https://bozeman.craigslist.org/"
                "modesto" "https://modesto.craigslist.org/"
                "tri-cities" "https://tricities.craigslist.org/"
                "minneapolis / st paul" "https://minneapolis.craigslist.org/"
                "bremen" "https://bremen.craigslist.de/"
                "seoul" "https://seoul.craigslist.co.kr/"
                "hilton head" "https://hiltonhead.craigslist.org/"
                "jackson" "https://jackson.craigslist.org/"
                "meridian" "https://meridian.craigslist.org/"
                "new hampshire" "https://nh.craigslist.org/"
                "whitehorse" "https://whitehorse.craigslist.ca/"
                "chico" "https://chico.craigslist.org/"
                "okinawa" "https://okinawa.craigslist.jp/"
                "western massachusetts" "https://westernmass.craigslist.org/"
                "washington" "https://washingtondc.craigslist.org/"
                "new york city" "https://newyork.craigslist.org/"
                "barrie" "https://barrie.craigslist.ca/"
                "perugia" "https://perugia.craigslist.it/"
                "berlin" "https://berlin.craigslist.de/"
                "central michigan" "https://centralmich.craigslist.org/"
                "waterloo / cedar falls" "https://waterloo.craigslist.org/"
                "houma" "https://houma.craigslist.org/"
                "appleton-oshkosh-FDL" "https://appleton.craigslist.org/"
                "peru" "https://lima.craigslist.org/"
                "tallahassee" "https://tallahassee.craigslist.org/"
                "austin" "https://austin.craigslist.org/"
                "gold country" "https://goldcountry.craigslist.org/"
                "winchester" "https://winchester.craigslist.org/"
                "fukuoka" "https://fukuoka.craigslist.jp/"
                "rockford" "https://rockford.craigslist.org/"
                "nashville" "https://nashville.craigslist.org/"
                "beirut lebanon" "https://beirut.craigslist.org/"
                "springfield" "https://springfield.craigslist.org/"
                "bellingham" "https://bellingham.craigslist.org/"
                "lehigh valley" "https://allentown.craigslist.org/"
                "cambridge UK" "https://cambridge.craigslist.co.uk/"
                "pensacola" "https://pensacola.craigslist.org/"
                "sierra vista" "https://sierravista.craigslist.org/"
                "medford-ashland" "https://medford.craigslist.org/"
                "spokane / coeur d'alene" "https://spokane.craigslist.org/"
                "anchorage / mat-su" "https://anchorage.craigslist.org/"
                "salvador bahia" "https://salvador.craigslist.org/"
                "lille" "https://lille.craigslist.org/"
                "atlanta" "https://atlanta.craigslist.org/"
                "brittany" "https://rennes.craigslist.org/"
                "bemidji" "https://bemidji.craigslist.org/"
                "scottsbluff / panhandle" "https://scottsbluff.craigslist.org/"
                "southeast KS" "https://seks.craigslist.org/"
                "regina" "https://regina.craigslist.ca/"
                "central louisiana" "https://cenla.craigslist.org/"
                "birmingham" "https://bham.craigslist.org/"
                "hickory / lenoir" "https://hickory.craigslist.org/"
                "chile" "https://santiago.craigslist.org/"
                "belfast" "https://belfast.craigslist.co.uk/"
                "springfield " "https://springfieldil.craigslist.org/"
                "sarnia" "https://sarnia.craigslist.ca/"
                "dallas / fort worth" "https://dallas.craigslist.org/"
                "south bend / michiana" "https://southbend.craigslist.org/"
                "potsdam-canton-massena" "https://potsdam.craigslist.org/"
                "buenos aires" "https://buenosaires.craigslist.org/"
                "jonesboro" "https://jonesboro.craigslist.org/"
                "northern michigan" "https://nmi.craigslist.org/"
                "sandusky" "https://sandusky.craigslist.org/"
                "auburn" "https://auburn.craigslist.org/"
                "moscow" "https://moscow.craigslist.org/"
                "bolivia" "https://lapaz.craigslist.org/"
                "wellington" "https://wellington.craigslist.org/"
                "st joseph" "https://stjoseph.craigslist.org/"
                "western KY" "https://westky.craigslist.org/"
                "duluth / superior" "https://duluth.craigslist.org/"
                "santa maria" "https://santamaria.craigslist.org/"
                "owensboro" "https://owensboro.craigslist.org/"
                "niagara region" "https://niagara.craigslist.ca/"
                "territories" "https://territories.craigslist.ca/"
                "victoria " "https://victoriatx.craigslist.org/"
                "frederick" "https://frederick.craigslist.org/"
                "venice / veneto" "https://venice.craigslist.it/"
                "meadville" "https://meadville.craigslist.org/"
                "lake of the ozarks" "https://loz.craigslist.org/"
                "newcastle NSW" "https://ntl.craigslist.com.au/"
                "portland" "https://portland.craigslist.org/"
                "luxembourg" "https://luxembourg.craigslist.org/"
                "williamsport" "https://williamsport.craigslist.org/"
                "tel aviv" "https://telaviv.craigslist.org/"
                "bulgaria" "https://bulgaria.craigslist.org/"
                "cornwall" "https://cornwall.craigslist.ca/"
                "terre haute" "https://terrehaute.craigslist.org/"
                "bakersfield" "https://bakersfield.craigslist.org/"
                "jackson " "https://jxn.craigslist.org/"
                "brantford-woodstock" "https://brantford.craigslist.ca/"
                "peterborough" "https://peterborough.craigslist.ca/"
                "amsterdam / randstad" "https://amsterdam.craigslist.org/"
                "sheboygan" "https://sheboygan.craigslist.org/"})

(defn get-regional-site [location]
  (get sites-map (string/lower-case location) "https://craigslist.org/"))

(defn fetch-craigslist-results [query location]
  (html/html-snippet
   (:body (http/get (str (get-regional-site location)
                         "search/sss?query="
                         (URLEncoder/encode query)
                         "&sort=rel")))))

(defn parse-craigslist-results [results]
  (let [result-rows (html/select results [:li.result-row])]
    (map (fn [row]
           (models/make-result
            (first (:content (first (html/select row [:a.result-title]))))
            (get-in (first (html/select row [:a.result-title])) [:attrs :href])
            (Integer/parseInt (apply str (rest (first (:content (first (html/select row [:span.result-price])))))))))
         result-rows)))

(defn search [query location]
  (parse-craigslist-results (fetch-craigslist-results query location)))

